apiVersion: elasticsearchdb.kaitoy.github.com/v1beta1
kind: Index
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: index-sample
url:
  elasticsearchEndpoint: http://elasticsearch:9200
  index: user
spec:
  settings:
    index:
      number_of_shards: 5
      number_of_replicas: 1
  mappings:
    _doc:
      _source:
        enabled: true
      properties:
        age:
          type: integer
        name:
          properties:
            first:
              type: keyword
              boost: 2.5
            last:
              type: keyword
